"use strict";
const fs=require("node:fs"),crypto=require("node:crypto"),cp=require("node:child_process"),path=require("node:path"),os=require("node:os");
const tool=JSON.parse(fs.readFileSync("toolchain.json","utf8")),provenance=JSON.parse(fs.readFileSync("vendor/toolchain/provenance.json","utf8"));
function sha(p){return crypto.createHash("sha256").update(fs.readFileSync(p)).digest("hex");}
const bundle="vendor/toolchain/compiler.git.bundle",elm="vendor/toolchain/elm-76bbe44424106c96f915cb24cd7f50d69f5cee0e-linux-x64",nodeArchive="vendor/toolchain/node-v24.4.1-linux-x64.xz",seed="vendor/toolchain/public-packages-0.19.2.tar.gz";
if(sha(bundle)!==tool.elmCompilerBundleSha256)throw Error("compiler bundle hash mismatch");
const bundleHeads=cp.execFileSync("git",["bundle","list-heads",bundle],{encoding:"utf8"});if(!bundleHeads.includes(provenance.compiler.bundle_head))throw Error("compiler bundle head mismatch");
const temp=fs.mkdtempSync(path.join(os.tmpdir(),"schelm-compiler-bundle-"));
try{cp.execFileSync("git",["clone","-q",bundle,temp]);const authorized=cp.execFileSync("git",["-C",temp,"show","-s","--format=%H %T %P",provenance.compiler.authorized_commit],{encoding:"utf8"}).trim();if(authorized!==`${provenance.compiler.authorized_commit} ${provenance.compiler.authorized_tree} ${tool.baseElmCommit}`)throw Error("authorized compiler commit/tree mismatch");const head=cp.execFileSync("git",["-C",temp,"show","-s","--format=%H %T %P",provenance.compiler.bundle_head],{encoding:"utf8"}).trim();if(head!==`${provenance.compiler.bundle_head} ${provenance.compiler.bundle_head_tree} ${provenance.compiler.authorized_commit}`)throw Error("compiler bundle ancestry mismatch");}finally{fs.rmSync(temp,{recursive:true,force:true});}
if(sha(elm)!==tool.elmCompilerBinarySha256)throw Error("compiler hash mismatch");if(sha(nodeArchive)!==tool.nodeArchiveSha256)throw Error("Node archive hash mismatch");if(sha(seed)!==tool.publicPackageSeedSha256)throw Error("seed hash mismatch");if(cp.execFileSync(elm,["--version"],{encoding:"utf8"}).trim()!==tool.elmLanguageVersion)throw Error("compiler version mismatch");if(process.version!==`v${tool.nodeVersion}`)throw Error(`run tests with Node ${tool.nodeVersion}, got ${process.version}`);const unpackHash=cp.execFileSync("sh",["-c",`xz -dc '${nodeArchive}' | sha256sum`],{encoding:"utf8"}).trim().split(/\s+/)[0];if(unpackHash!==tool.nodeBinarySha256)throw Error("Node archive payload hash mismatch");
const text=fs.readFileSync("scripts/prepare-overlay.cjs","utf8");if(text.includes(".elm/"))throw Error("ambient Elm cache reference");
console.log("offline provenance passed: compiler commit/tree ancestry, Elm binary, Node archive/executable, and public seed verified");
