"use strict";
const test=require("node:test"),assert=require("node:assert/strict");const {harness,bytes,settle}=require("../support/machine-harness.cjs");
function partitions(xs){if(!xs.length)return[[]];const out=[];for(let mask=0;mask<1<<(xs.length-1);mask++){const p=[];let cur=[xs[0]];for(let i=1;i<xs.length;i++){if(mask&(1<<(i-1))){p.push(cur);cur=[];}cur.push(xs[i]);}p.push(cur);out.push(p);}return out;}
test("all 2^(n-1) small partitions preserve complete bytes",async()=>{let cases=0;for(let n=0;n<=10;n++){const source=Array.from({length:n},(_,i)=>i);for(const p of partitions(source)){const h=harness({limit:10,chunks:p.map(bytes)});await settle();assert.deepEqual(h.deliveries,[{ok:true,value:{status:200,bodyKind:"complete",body:source,lower:n}}]);cases++;}}assert.equal(cases,1024);});
test("truncate and reject stop at first proven excess",async()=>{for(let limit=1;limit<=16;limit++)for(let n=limit+1;n<=limit+8;n++){const source=Array.from({length:n},(_,i)=>i%256),p=[source.slice(0,Math.max(1,limit-1)),source.slice(Math.max(1,limit-1))].map(bytes);let h=harness({limit,truncate:true,chunks:p});await settle();assert.equal(h.deliveries.length,1);assert.equal(h.deliveries[0].value.bodyKind,"truncated");assert.deepEqual(h.deliveries[0].value.body,source.slice(0,limit));assert.equal(h.deliveries[0].value.lower,limit+1);h=harness({limit,chunks:p});await settle();assert.equal(h.deliveries[0].error.kind,"response-too-large");}});
test("deadline claims before abort race",async()=>{const h=harness({fetchPending:true,abortThrows:true});await new Promise(r=>setImmediate(r));h.fireTimer();await settle();assert.equal(h.deliveries.length,1);assert.equal(h.deliveries[0].error.kind,"deadline-exceeded");assert.equal(h.events.filter(x=>x.event==="CallbackQueued").length,1);});
test("kill before callback yields no delivery and cleanup is idempotent",async()=>{const h=harness({chunks:[bytes([1])]});h.operation.kill();h.operation.kill();await settle();assert.equal(h.deliveries.length,0);assert.equal(h.operation.phase(),"Absent");assert.ok(h.counts().aborts<=1);});
test("redirect discard and bodyless statuses never read",async()=>{for(const spec of [{status:301,hasLocation:true,discardRedirectBody:true},{status:204},{status:304},{status:200,method:"HEAD"},{status:300,hasLocation:true,discardRedirectBody:true}]){const h=harness({...spec,chunks:[bytes([1])]});await settle();if(spec.status===300)assert.equal(h.counts().reads,2);else assert.equal(h.counts().reads,0);}});
test("constructive errors never expose exception text",async()=>{const h=harness({fetchReject:true,code:"ECONNRESET"});await settle();assert.deepEqual(h.deliveries,[{ok:false,error:{kind:"network-failure",site:"fetch",code:"ECONNRESET"}}]);assert.ok(!JSON.stringify(h.deliveries).includes("secret-fetch"));});
